# Generated by Django 5.1.2 on 2024-12-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_note_delete_savedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
    ]
